from argparse import Namespace


def make_args(**overrides):
    values = dict(
        hidden_size=16,
        gain=0.01,
        use_orthogonal=True,
        use_policy_active_masks=True,
        use_naive_recurrent_policy=False,
        use_recurrent_policy=True,
        recurrent_N=1,
        use_feature_normalization=True,
        use_ReLU=True,
        stacked_frames=1,
        use_stacked_frames=False,
        layer_N=1,
        algorithm_name="cstm_mappo",
        cstm_latent_dim=8,
        cstm_aux_coef=0.1,
        cstm_num_heads=1,
        cstm_bootstrap_prob=0.8,
        cstm_random_prior_scale=0.0,
        cstm_ood_rank_coef=0.0,
        cstm_ood_rank_margin=0.02,
        cstm_ood_noise_std=0.2,
        cstm_ood_mask_prob=0.3,
        cstm_ood_delay_prob=0.0,
        cstm_uncertainty_cal_coef=0.0,
        cstm_uncertainty_target_scale=0.05,
        cstm_uncertainty_corr_coef=0.0,
        cstm_use_uncertainty_feature=False,
        cstm_use_teammate_policy=True,
        num_agents=3,
        episode_length=4,
        n_rollout_threads=2,
        gamma=0.99,
        gae_lambda=0.95,
        use_gae=True,
        use_popart=False,
        use_valuenorm=False,
        use_proper_time_limits=False,
    )
    values.update(overrides)
    return Namespace(**values)
